name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    # runs-on: [pytorch/pytorch]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        # env:
          # REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # run:
            # using: "composite"
            # steps:
                # - run: pip install -r requirements.txt > /dev/null
                  # shell: bash
                # - run: python main.py
                  # shell: bash
                # - run: |
                    # cat ./artifacts/log.txt >> report.md
                    # cml-publish ./artifacts/plot.png --md >> report.md
                    # cml-send-comment report.md
                  # shell: bash
        run: |
          pip install -r requirements.txt > /dev/null
          python main.py
          depth = 5
          cat ./artifacts/log.txt >> report.md
          cml-publish ./artifacts/plot.png --md >> report.md
          cml-send-comment report.md
