name: model-training
on: [push]
jobs:
  run:
    # runs-on: [ubuntu-latest]
    runs-on: [pytorch/pytorch]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        # env:
          # REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        installs: pip install -r requirements.txt > /dev/null
        run: python main.py
        exports: |
            cat ./artifacts/log.txt >> report.md
            cml-publish ./artifacts/plot.png --md >> report.md
            cml-send-comment report.md
        # run: |
          # pip install -r requirements.txt > /dev/null
          # python main.py
          # depth = 5
          # cat ./artifacts/log.txt >> report.md
          # cml-publish ./artifacts/plot.png --md >> report.md
          # cml-send-comment report.md
